name: x
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.7+2
  http: ^0.12.1
  custom_switch: ^0.0.1
  url_launcher: ^5.4.7  
  fluttertoast: ^6.0.1
  intl_phone_field: ^1.2.0
  pin_input_text_field: ^3.0.4
  polygon_clipper: ^1.0.2
  cached_network_image: ^2.2.0+1
  google_fonts: ^1.1.0
  expansion_card: ^0.1.0
  intl: ^0.16.1
  # flutter_parse: ^0.2.3
  parse_server_sdk: ^1.0.26
  data_tables: ^1.0.3
  responsive_table: ^0.1.1+8
  provider: ^4.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/

  fonts:
    - family: pds
      fonts:
        - asset: assets/pds.ttf